### ISSUE TITLE
Can't load world properly after logging back in

### ISSUE THREAD

**Issue by viet** [minecraftly/minecraftly#2]
- Frequency: sometimes

```java
[06:05:06 ERROR]: Couldn't save chunk; already in use by another instance of Minecraft?
net.minecraft.server.v1_8_R3.ExceptionWorldConflict: The save for world located at /m/worlds/696f8b26-c97b-4e0c-b8f2-a1938d469701 is being accessed from another location, aborting
        at net.minecraft.server.v1_8_R3.WorldNBTStorage.checkSession(WorldNBTStorage.java:72) ~[spigot.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.World.checkSession(World.java:2970) ~[spigot.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.ChunkRegionLoader.a(ChunkRegionLoader.java:121) ~[spigot.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.ChunkProviderServer.saveChunk(ChunkProviderServer.java:268) [spigot.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.ChunkProviderServer.unloadChunks(ChunkProviderServer.java:374) [spigot.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.WorldServer.doTick(WorldServer.java:234) [spigot.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:830) [spigot.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [spigot.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) [spigot.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [spigot.jar:git-PaperSpigot-"8b18730"]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_74]
[06:05:06 ERROR]: Couldn't save chunk; already in use by another instance of Minecraft?
net.minecraft.server.v1_8_R3.ExceptionWorldConflict: The save for world located at /m/worlds/696f8b26-c97b-4e0c-b8f2-a1938d469701 is being accessed from another location, aborting
        at net.minecraft.server.v1_8_R3.WorldNBTStorage.checkSession(WorldNBTStorage.java:72) ~[spigot.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.World.checkSession(World.java:2970) ~[spigot.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.ChunkRegionLoader.a(ChunkRegionLoader.java:121) ~[spigot.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.ChunkProviderServer.saveChunk(ChunkProviderServer.java:268) [spigot.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.ChunkProviderServer.unloadChunks(ChunkProviderServer.java:374) [spigot.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.WorldServer.doTick(WorldServer.java:234) [spigot.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:830) [spigot.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [spigot.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) [spigot.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [spigot.jar:git-PaperSpigot-"8b18730"]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_74]
[06:05:06 ERROR]: Couldn't save chunk; already in use by another instance of Minecraft?
net.minecraft.server.v1_8_R3.ExceptionWorldConflict: The save for world located at /m/worlds/696f8b26-c97b-4e0c-b8f2-a1938d469701 is being accessed from another location, aborting
        at net.minecraft.server.v1_8_R3.WorldNBTStorage.checkSession(WorldNBTStorage.java:72) ~[spigot.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.World.checkSession(World.java:2970) ~[spigot.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.ChunkRegionLoader.a(ChunkRegionLoader.java:121) ~[spigot.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.ChunkProviderServer.saveChunk(ChunkProviderServer.java:268) [spigot.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.ChunkProviderServer.unloadChunks(ChunkProviderServer.java:374) [spigot.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.WorldServer.doTick(WorldServer.java:234) [spigot.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:830) [spigot.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [spigot.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) [spigot.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [spigot.jar:git-PaperSpigot-"8b18730"]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_74]
[06:05:06 ERROR]: Couldn't save chunk; already in use by another instance of Minecraft?
net.minecraft.server.v1_8_R3.ExceptionWorldConflict: The save for world located at /m/worlds/696f8b26-c97b-4e0c-b8f2-a1938d469701 is being accessed from another location, aborting
        at net.minecraft.server.v1_8_R3.WorldNBTStorage.checkSession(WorldNBTStorage.java:72) ~[spigot.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.World.checkSession(World.java:2970) ~[spigot.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.ChunkRegionLoader.a(ChunkRegionLoader.java:121) ~[spigot.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.ChunkProviderServer.saveChunk(ChunkProviderServer.java:268) [spigot.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.ChunkProviderServer.unloadChunks(ChunkProviderServer.java:374) [spigot.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.WorldServer.doTick(WorldServer.java:234) [spigot.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:830) [spigot.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [spigot.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) [spigot.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [spigot.jar:git-PaperSpigot-"8b18730"]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_74]
[06:05:06 ERROR]: Couldn't save chunk; already in use by another instance of Minecraft?
net.minecraft.server.v1_8_R3.ExceptionWorldConflict: The save for world located at /m/worlds/696f8b26-c97b-4e0c-b8f2-a1938d469701 is being accessed from another location, aborting
        at net.minecraft.server.v1_8_R3.WorldNBTStorage.checkSession(WorldNBTStorage.java:72) ~[spigot.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.World.checkSession(World.java:2970) ~[spigot.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.ChunkRegionLoader.a(ChunkRegionLoader.java:121) ~[spigot.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.ChunkProviderServer.saveChunk(ChunkProviderServer.java:268) [spigot.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.ChunkProviderServer.unloadChunks(ChunkProviderServer.java:374) [spigot.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.WorldServer.doTick(WorldServer.java:234) [spigot.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:830) [spigot.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [spigot.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) [spigot.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [spigot.jar:git-PaperSpigot-"8b18730"]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_74]
[06:05:06 ERROR]: Couldn't save chunk; already in use by another instance of Minecraft?
net.minecraft.server.v1_8_R3.ExceptionWorldConflict: The save for world located at /m/worlds/696f8b26-c97b-4e0c-b8f2-a1938d469701 is being accessed from another location, aborting
        at net.minecraft.server.v1_8_R3.WorldNBTStorage.checkSession(WorldNBTStorage.java:72) ~[spigot.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.World.checkSession(World.java:2970) ~[spigot.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.ChunkRegionLoader.a(ChunkRegionLoader.java:121) ~[spigot.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.ChunkProviderServer.saveChunk(ChunkProviderServer.java:268) [spigot.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.ChunkProviderServer.unloadChunks(ChunkProviderServer.java:374) [spigot.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.WorldServer.doTick(WorldServer.java:234) [spigot.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:830) [spigot.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [spigot.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) [spigot.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [spigot.jar:git-PaperSpigot-"8b18730"]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_74]
[06:05:06 ERROR]: Couldn't save chunk; already in use by another instance of Minecraft?
net.minecraft.server.v1_8_R3.ExceptionWorldConflict: The save for world located at /m/worlds/696f8b26-c97b-4e0c-b8f2-a1938d469701 is being accessed from another location, aborting
        at net.minecraft.server.v1_8_R3.WorldNBTStorage.checkSession(WorldNBTStorage.java:72) ~[spigot.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.World.checkSession(World.java:2970) ~[spigot.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.ChunkRegionLoader.a(ChunkRegionLoader.java:121) ~[spigot.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.ChunkProviderServer.saveChunk(ChunkProviderServer.java:268) [spigot.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.ChunkProviderServer.unloadChunks(ChunkProviderServer.java:374) [spigot.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.WorldServer.doTick(WorldServer.java:234) [spigot.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:830) [spigot.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [spigot.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) [spigot.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [spigot.jar:git-PaperSpigot-"8b18730"]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_74]
[06:05:06 ERROR]: Couldn't save chunk; already in use by another instance of Minecraft?
net.minecraft.server.v1_8_R3.ExceptionWorldConflict: The save for world located at /m/worlds/696f8b26-c97b-4e0c-b8f2-a1938d469701 is being accessed from another location, aborting
        at net.minecraft.server.v1_8_R3.WorldNBTStorage.checkSession(WorldNBTStorage.java:72) ~[spigot.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.World.checkSession(World.java:2970) ~[spigot.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.ChunkRegionLoader.a(ChunkRegionLoader.java:121) ~[spigot.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.ChunkProviderServer.saveChunk(ChunkProviderServer.java:268) [spigot.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.ChunkProviderServer.unloadChunks(ChunkProviderServer.java:374) [spigot.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.WorldServer.doTick(WorldServer.java:234) [spigot.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:830) [spigot.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [spigot.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) [spigot.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [spigot.jar:git-PaperSpigot-"8b18730"]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_74]
[06:05:06 ERROR]: Couldn't save chunk; already in use by another instance of Minecraft?
net.minecraft.server.v1_8_R3.ExceptionWorldConflict: The save for world located at /m/worlds/696f8b26-c97b-4e0c-b8f2-a1938d469701 is being accessed from another location, aborting
        at net.minecraft.server.v1_8_R3.WorldNBTStorage.checkSession(WorldNBTStorage.java:72) ~[spigot.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.World.checkSession(World.java:2970) ~[spigot.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.ChunkRegionLoader.a(ChunkRegionLoader.java:121) ~[spigot.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.ChunkProviderServer.saveChunk(ChunkProviderServer.java:268) [spigot.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.ChunkProviderServer.unloadChunks(ChunkProviderServer.java:374) [spigot.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.WorldServer.doTick(WorldServer.java:234) [spigot.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:830) [spigot.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [spigot.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) [spigot.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [spigot.jar:git-PaperSpigot-"8b18730"]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_74]
[06:05:06 ERROR]: Couldn't save chunk; already in use by another instance of Minecraft?
net.minecraft.server.v1_8_R3.ExceptionWorldConflict: The save for world located at /m/worlds/696f8b26-c97b-4e0c-b8f2-a1938d469701 is being accessed from another location, aborting
        at net.minecraft.server.v1_8_R3.WorldNBTStorage.checkSession(WorldNBTStorage.java:72) ~[spigot.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.World.checkSession(World.java:2970) ~[spigot.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.ChunkRegionLoader.a(ChunkRegionLoader.java:121) ~[spigot.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.ChunkProviderServer.saveChunk(ChunkProviderServer.java:268) [spigot.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.ChunkProviderServer.unloadChunks(ChunkProviderServer.java:374) [spigot.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.WorldServer.doTick(WorldServer.java:234) [spigot.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:830) [spigot.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [spigot.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) [spigot.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [spigot.jar:git-PaperSpigot-"8b18730"]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_74]
[06:05:06 ERROR]: Couldn't save chunk; already in use by another instance of Minecraft?
net.minecraft.server.v1_8_R3.ExceptionWorldConflict: The save for world located at /m/worlds/696f8b26-c97b-4e0c-b8f2-a1938d469701 is being accessed from another location, aborting
        at net.minecraft.server.v1_8_R3.WorldNBTStorage.checkSession(WorldNBTStorage.java:72) ~[spigot.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.World.checkSession(World.java:2970) ~[spigot.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.ChunkRegionLoader.a(ChunkRegionLoader.java:121) ~[spigot.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.ChunkProviderServer.saveChunk(ChunkProviderServer.java:268) [spigot.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.ChunkProviderServer.unloadChunks(ChunkProviderServer.java:374) [spigot.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.WorldServer.doTick(WorldServer.java:234) [spigot.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:830) [spigot.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [spigot.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) [spigot.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [spigot.jar:git-PaperSpigot-"8b18730"]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_74]
[06:05:06 ERROR]: Couldn't save chunk; already in use by another instance of Minecraft?
net.minecraft.server.v1_8_R3.ExceptionWorldConflict: The save for world located at /m/worlds/696f8b26-c97b-4e0c-b8f2-a1938d469701 is being accessed from another location, aborting
        at net.minecraft.server.v1_8_R3.WorldNBTStorage.checkSession(WorldNBTStorage.java:72) ~[spigot.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.World.checkSession(World.java:2970) ~[spigot.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.ChunkRegionLoader.a(ChunkRegionLoader.java:121) ~[spigot.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.ChunkProviderServer.saveChunk(ChunkProviderServer.java:268) [spigot.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.ChunkProviderServer.unloadChunks(ChunkProviderServer.java:374) [spigot.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.WorldServer.doTick(WorldServer.java:234) [spigot.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:830) [spigot.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [spigot.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) [spigot.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [spigot.jar:git-PaperSpigot-"8b18730"]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_74]
[06:05:06 ERROR]: Couldn't save chunk; already in use by another instance of Minecraft?
net.minecraft.server.v1_8_R3.ExceptionWorldConflict: The save for world located at /m/worlds/696f8b26-c97b-4e0c-b8f2-a1938d469701 is being accessed from another location, aborting
        at net.minecraft.server.v1_8_R3.WorldNBTStorage.checkSession(WorldNBTStorage.java:72) ~[spigot.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.World.checkSession(World.java:2970) ~[spigot.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.ChunkRegionLoader.a(ChunkRegionLoader.java:121) ~[spigot.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.ChunkProviderServer.saveChunk(ChunkProviderServer.java:268) [spigot.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.ChunkProviderServer.unloadChunks(ChunkProviderServer.java:374) [spigot.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.WorldServer.doTick(WorldServer.java:234) [spigot.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:830) [spigot.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [spigot.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) [spigot.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [spigot.jar:git-PaperSpigot-"8b18730"]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_74]
[06:05:06 ERROR]: Couldn't save chunk; already in use by another instance of Minecraft?
net.minecraft.server.v1_8_R3.ExceptionWorldConflict: The save for world located at /m/worlds/696f8b26-c97b-4e0c-b8f2-a1938d469701 is being accessed from another location, aborting
        at net.minecraft.server.v1_8_R3.WorldNBTStorage.checkSession(WorldNBTStorage.java:72) ~[spigot.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.World.checkSession(World.java:2970) ~[spigot.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.ChunkRegionLoader.a(ChunkRegionLoader.java:121) ~[spigot.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.ChunkProviderServer.saveChunk(ChunkProviderServer.java:268) [spigot.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.ChunkProviderServer.unloadChunks(ChunkProviderServer.java:374) [spigot.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.WorldServer.doTick(WorldServer.java:234) [spigot.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:830) [spigot.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [spigot.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) [spigot.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [spigot.jar:git-PaperSpigot-"8b18730"]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_74]
[06:05:06 ERROR]: Couldn't save chunk; already in use by another instance of Minecraft?
net.minecraft.server.v1_8_R3.ExceptionWorldConflict: The save for world located at /m/worlds/696f8b26-c97b-4e0c-b8f2-a1938d469701 is being accessed from another location, aborting
        at net.minecraft.server.v1_8_R3.WorldNBTStorage.checkSession(WorldNBTStorage.java:72) ~[spigot.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.World.checkSession(World.java:2970) ~[spigot.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.ChunkRegionLoader.a(ChunkRegionLoader.java:121) ~[spigot.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.ChunkProviderServer.saveChunk(ChunkProviderServer.java:268) [spigot.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.ChunkProviderServer.unloadChunks(ChunkProviderServer.java:374) [spigot.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.WorldServer.doTick(WorldServer.java:234) [spigot.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:830) [spigot.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [spigot.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) [spigot.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [spigot.jar:git-PaperSpigot-"8b18730"]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_74]
[06:05:09 INFO]: [PlayerWorlds] Unloaded world for player: 696f8b26-c97b-4e0c-b8f2-a1938d469701.
aborting
        at net.minecraft.server.v1_8_R3.WorldNBTStorage.checkSession(WorldNBTStorage.java:72) ~[spigot.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.World.checkSession(World.java:2970) ~[spigot.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.ChunkRegionLoader.a(ChunkRegionLoader.java:121) ~[spigot.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.ChunkProviderServer.saveChunk(ChunkProviderServer.java:268) [spigot.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.ChunkProviderServer.unloadChunks(ChunkProviderServer.java:374) [spigot.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.WorldServer.doTick(WorldServer.java:234) [spigot.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:830) [spigot.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [spigot.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) [spigot.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [spigot.jar:git-PaperSpigot-"8b18730"]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_74]
[06:05:09 INFO]: [PlayerWorlds] Unloaded world for player: 696f8b26-c97b-4e0c-b8f2-a1938d469701.
[06:05:09 ERROR]: null
net.minecraft.server.v1_8_R3.ExceptionWorldConflict: The save for world located at /m/worlds/696f8b26-c97b-4e0c-b8f2-a1938d469701 is being accessed from another location, aborting
        at net.minecraft.server.v1_8_R3.WorldNBTStorage.checkSession(WorldNBTStorage.java:72) ~[spigot.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.World.checkSession(World.java:2970) ~[spigot.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.WorldServer.a(WorldServer.java:984) ~[spigot.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.WorldServer.save(WorldServer.java:956) ~[spigot.jar:git-PaperSpigot-"8b18730"]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.unloadWorld(CraftServer.java:999) [spigot.jar:git-PaperSpigot-"8b18730"]
        at org.bukkit.Bukkit.unloadWorld(Bukkit.java:507) [spigot.jar:git-PaperSpigot-"8b18730"]
        at com.minecraftly.bukkit.modules.playerworlds.handlers.PlayerListener.checkWorldForUnload(PlayerListener.java:198) [Minecraftly.jar:?]
        at com.minecraftly.bukkit.modules.playerworlds.handlers.PlayerListener$3.run(PlayerListener.java:191) [Minecraftly.jar:?]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59) [spigot.jar:git-PaperSpigot-"8b18730"]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:349) [spigot.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:783) [spigot.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [spigot.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) [spigot.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [spigot.jar:git-PaperSpigot-"8b18730"]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_74]
```

**Comment by SilverCory** [comment]
Is it unloaded properly?

**Comment by viet** [comment]
@SilverCory: From what I can tell, most of the time yes.

**Comment by SilverCory** [comment]
Bet's on this one reoccurring? xD

**Comment by viet** [comment]
I hope not haha. Double world loading is the most annoying thing for users ever!

**Comment by SilverCory** [comment]
For everyone, not just users xD
