### ISSUE TITLE
Double world loading when running 2 instances

### ISSUE THREAD

**Issue by viet** [minecraftly/minecraftly#56]
I got this when running 2 instances of spigot servers
```
[09:38:51 INFO]: VietNguyen[/10.20.0.1:42683] logged in with entity id 65485 at ([b7de0a32-064c-45da-bd08-1120b7ff465b]703.5604715241536, 73.0, -914.6999999880791)
[09:38:51 INFO]: Using world b7de0a32-064c-45da-bd08-1120b7ff465b for VietNguyen|| Spawn location: Location{world=CraftWorld{name=b7de0a32-064c-45da-bd08-1120b7ff465b},x=720.0,y=83.0,z=-923.0,pitch=0.0,yaw=0.0}
[09:38:54 ERROR]: Couldn't save chunk; already in use by another instance of Minecraft?
net.minecraft.server.v1_10_R1.ExceptionWorldConflict: The save for world located at /mnt/worlds/world is being accessed from another location, aborting
        at net.minecraft.server.v1_10_R1.WorldNBTStorage.checkSession(WorldNBTStorage.java:78) ~[patched_1.10.2.jar:git-Paper-837]
        at net.minecraft.server.v1_10_R1.World.checkSession(World.java:2974) ~[patched_1.10.2.jar:git-Paper-837]
        at net.minecraft.server.v1_10_R1.ChunkRegionLoader.a(ChunkRegionLoader.java:132) ~[patched_1.10.2.jar:git-Paper-837]
        at net.minecraft.server.v1_10_R1.ChunkProviderServer.saveChunk(ChunkProviderServer.java:237) [patched_1.10.2.jar:git-Paper-837]
        at net.minecraft.server.v1_10_R1.ChunkProviderServer.unloadChunk(ChunkProviderServer.java:349) [patched_1.10.2.jar:git-Paper-837]
        at net.minecraft.server.v1_10_R1.ChunkProviderServer.unloadChunks(ChunkProviderServer.java:293) [patched_1.10.2.jar:git-Paper-837]
        at net.minecraft.server.v1_10_R1.WorldServer.doTick(WorldServer.java:243) [patched_1.10.2.jar:git-Paper-837]
        at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:843) [patched_1.10.2.jar:git-Paper-837]
        at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:404) [patched_1.10.2.jar:git-Paper-837]
        at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:725) [patched_1.10.2.jar:git-Paper-837]
        at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:624) [patched_1.10.2.jar:git-Paper-837]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
```

**Comment by SilverCory** [comment]
#22 I'm pretty sure is the same error
