### ISSUE TITLE
1.9 BungeeCord Compability

### ISSUE THREAD

**Issue by viet** [minecraftly/minecraftly#7]
MinecraftlyBungee is currently not compatible with the latest BungeeCord on March 11, 2016.

``` java
17:08:07 [SEVERE] [MinecraftlyBungee] Error whilst applying reflection for default server.
java.lang.NoSuchFieldException: defaultServer
    at java.lang.Class.getDeclaredField(Class.java:2070)
    at com.minecraftly.bungee.utilities.BungeeUtilities.setListenerInfoField(BungeeUtilities.java:75)
    at com.minecraftly.bungee.MclyCoreBungeePlugin.onEnable(MclyCoreBungeePlugin.java:139)
    at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:227)
    at net.md_5.bungee.BungeeCord.start(BungeeCord.java:260)
    at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:55)
    at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
17:08:07 [INFO] Enabled plugin MinecraftlyBungee version 1.0-SNAPSHOT by Minecraftly Network

08:00:37 [WARNING] Exception encountered when loading plugin: MinecraftlyBungee
java.lang.UnsupportedOperationException
    at java.util.AbstractMap.put(AbstractMap.java:209)
    at net.md_5.bungee.config.Configuration.set(Configuration.java:97)
    at com.minecraftly.bungee.utilities.BungeeUtilities.copyDefaults(BungeeUtilities.java:108)
    at com.minecraftly.bungee.utilities.BungeeUtilities.copyDefaults(BungeeUtilities.java:104)
    at com.minecraftly.bungee.utilities.BungeeUtilities.copyDefaultsFromJarFile(BungeeUtilities.java:87)
    at com.minecraftly.bungee.utilities.BungeeUtilities.copyDefaultsFromJarFile(BungeeUtilities.java:83)
    at com.minecraftly.bungee.MclyCoreBungeePlugin.onEnable(MclyCoreBungeePlugin.java:104)
    at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:227)
    at net.md_5.bungee.BungeeCord.start(BungeeCord.java:260)
    at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:55)
    at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
```

**Comment by viet** [comment]
Yes! Ben @redraskal is taking care of it: https://www.bountysource.com/issues/32530930
